# Generated by Django 5.2.14 on 2026-05-18 02:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterEvalRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('prompt_hash', models.CharField(db_index=True, max_length=64)),
                ('prompt_content', models.TextField()),
                ('model', models.CharField(max_length=64)),
                ('eval_set_size', models.PositiveIntegerField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1', models.FloatField()),
                ('metrics_by_tier', models.JSONField(blank=True, default=dict)),
                ('eval_set_snapshot', models.JSONField(blank=True, default=list)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_duration_s', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FilterClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_hash', models.CharField(db_index=True, max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('classified_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_opportunity', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('reason', models.TextField()),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cached_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('verdict_band', models.CharField(choices=[('high_yes', 'High yes'), ('high_no', 'High no'), ('uncertain', 'Uncertain')], max_length=16)),
                ('discarded', models.BooleanField(default=False)),
                ('discard_reason', models.CharField(blank=True, choices=[('below_threshold', 'Below threshold'), ('structural_prefilter', 'Structural prefilter'), ('duplicate', 'Duplicate')], max_length=32, null=True)),
                ('human_label', models.JSONField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='clusters.clusteritem')),
            ],
        ),
        migrations.CreateModel(
            name='FilterEvalSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('content_context', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(max_length=64)),
                ('human_label', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('ambiguous', 'Ambiguous'), ('adversarial', 'Adversarial')], max_length=16)),
                ('human_confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=8, null=True)),
                ('difficulty_tier', models.CharField(choices=[('clear_yes', 'Clear yes'), ('clear_no', 'Clear no'), ('ambiguous', 'Ambiguous'), ('adversarial', 'Adversarial')], max_length=16)),
                ('reasoning_note', models.TextField(blank=True, null=True)),
                ('labeled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_revised_at', models.DateTimeField(blank=True, null=True)),
                ('sourced_from', models.CharField(choices=[('production_classification', 'Production classification'), ('hand_curated', 'Hand curated'), ('imported', 'Imported')], max_length=32)),
                ('labeled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_eval_items_labeled', to=settings.AUTH_USER_MODEL)),
                ('production_classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eval_items', to='ingestion.filterclassification')),
            ],
        ),
        migrations.CreateModel(
            name='FilterEvalClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_verdict', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=8)),
                ('model_confidence', models.FloatField()),
                ('model_reason', models.TextField()),
                ('agrees_with_label', models.BooleanField()),
                ('eval_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='ingestion.filterevalrun')),
                ('eval_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_classifications', to='ingestion.filterevalset')),
            ],
        ),
    ]
