# Generated by Django 5.2.14 on 2026-05-18 02:41

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=64)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('rerun', 'Rerun'), ('eval', 'Eval')], max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('killed', 'Killed'), ('budget_exhausted', 'Budget exhausted')], default='running', max_length=24)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_max_steps', models.PositiveIntegerField()),
                ('budget_max_cost_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('budget_max_duration_s', models.PositiveIntegerField()),
                ('steps_used', models.PositiveIntegerField(default=0)),
                ('cost_used_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('duration_used_s', models.PositiveIntegerField(default=0)),
                ('final_output', models.JSONField(blank=True, null=True)),
                ('termination_reason', models.CharField(blank=True, choices=[('agent_decided_done', 'Agent decided done'), ('budget_steps', 'Budget exhausted (steps)'), ('budget_cost', 'Budget exhausted (cost)'), ('budget_duration', 'Budget exhausted (duration)'), ('error', 'Error'), ('killed_by_human', 'Killed by human'), ('tool_failure_cascade', 'Tool failure cascade'), ('loop_detected', 'Loop detected'), ('schema_validation_failed', 'Schema validation failed'), ('model_api_failure', 'Model API failure'), ('worker_crashed', 'Worker crashed')], max_length=32, null=True)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('models_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('eval_run_id', models.UUIDField(blank=True, null=True)),
                ('human_label', models.JSONField(blank=True, null=True)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('config_snapshot', models.JSONField()),
                ('cluster_snapshot', models.JSONField()),
                ('prompt_hashes', models.JSONField(blank=True, default=dict)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='clusters.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('step_type', models.CharField(choices=[('tool_call', 'Tool call'), ('model_reasoning_only', 'Model reasoning only'), ('final_output', 'Final output')], max_length=32)),
                ('tool_name', models.CharField(blank=True, max_length=64, null=True)),
                ('tool_input', models.JSONField(blank=True, null=True)),
                ('tool_output_summary', models.TextField(blank=True, null=True)),
                ('tool_output_full_ref', models.CharField(blank=True, max_length=256, null=True)),
                ('tool_status', models.CharField(blank=True, choices=[('success', 'Success'), ('error', 'Error'), ('rate_limited', 'Rate limited'), ('timeout', 'Timeout'), ('validation_failed', 'Validation failed')], max_length=24, null=True)),
                ('tool_retry_count', models.PositiveIntegerField(default=0)),
                ('was_cached', models.BooleanField(default=False)),
                ('cache_age_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cached_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('model', models.CharField(blank=True, max_length=64, null=True)),
                ('cumulative_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cumulative_steps', models.PositiveIntegerField(default=0)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agents.agentrun')),
            ],
        ),
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('model_request', 'Model request'), ('model_response', 'Model response'), ('model_thinking', 'Model thinking'), ('tool_request', 'Tool request'), ('tool_response', 'Tool response'), ('tool_error', 'Tool error'), ('guardrail_triggered', 'Guardrail triggered'), ('budget_warning', 'Budget warning'), ('human_intervention', 'Human intervention')], max_length=32)),
                ('payload', models.JSONField()),
                ('payload_size_bytes', models.PositiveIntegerField(default=0)),
                ('prompt_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('response_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('tool_name', models.CharField(blank=True, max_length=64, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agents.agentrun')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agents.agentstep')),
            ],
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['cluster', 'started_at'], name='agents_agen_cluster_da1603_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=django.contrib.postgres.indexes.GinIndex(fields=['prompt_hashes'], name='agentrun_prompts_gin'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['run', 'step_number'], name='agents_agen_run_id_98f2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['tool_name', 'started_at'], name='agents_agen_tool_na_dab0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(condition=models.Q(('tool_status', 'error')), fields=['tool_status'], name='agentstep_tool_err_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentstep',
            constraint=models.UniqueConstraint(fields=('run', 'step_number'), name='agentstep_run_stepnum_unique'),
        ),
        migrations.AddIndex(
            model_name='agentevent',
            index=models.Index(fields=['step', 'sequence'], name='agents_agen_step_id_526c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentevent',
            index=models.Index(fields=['run', 'recorded_at'], name='agents_agen_run_id_c06e1d_idx'),
        ),
    ]
