# Generated by Django 6.0.5 on 2026-05-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentstep',
            name='tool_status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('error', 'Error'), ('rate_limited', 'Rate limited'), ('timeout', 'Timeout'), ('not_found', 'Not found'), ('validation_failed', 'Validation failed')], max_length=24, null=True),
        ),
    ]
