# Generated by Django 6.0.5 on 2026-05-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apikey',
            new_name='api_apikey_user_id_58cac9_idx',
            old_name='api_apikey_user_id_revoked_idx',
        ),
    ]
