# Generated by Django 5.2.14 on 2026-05-18 02:41

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('clusters', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_review', 'Awaiting review'), ('promoted', 'Promoted'), ('rejected', 'Rejected'), ('stale', 'Stale'), ('superseded', 'Superseded')], default='awaiting_review', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('supporting_run_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('brief', models.JSONField()),
                ('brief_schema_version', models.CharField(default='1.0', max_length=16)),
                ('cluster_snapshot', models.JSONField()),
                ('human_decision', models.JSONField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('stale_reason', models.CharField(blank=True, choices=[('prompt_changed', 'Prompt changed'), ('cluster_changed', 'Cluster changed'), ('age', 'Age'), ('manual', 'Manual')], max_length=24, null=True)),
                ('stale_marked_at', models.DateTimeField(blank=True, null=True)),
                ('build_status', models.CharField(blank=True, choices=[('not_pursued', 'Not pursued'), ('researching_further', 'Researching further'), ('building', 'Building'), ('shipped', 'Shipped'), ('abandoned', 'Abandoned')], max_length=24, null=True)),
                ('build_status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('build_notes', models.TextField(blank=True, null=True)),
                ('in_eval_set', models.BooleanField(default=False)),
                ('eval_set_notes', models.TextField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='clusters.cluster')),
                ('decided_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations_decided', to=settings.AUTH_USER_MODEL)),
                ('primary_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_investigations', to='agents.agentrun')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='investigations.investigation')),
            ],
        ),
    ]
