# Generated by Django 5.2.14 on 2026-05-18 02:40

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_pgvector_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Investigating'), ('investigated', 'Investigated'), ('discarded', 'Discarded'), ('merged_into', 'Merged into'), ('split', 'Split')], default='pending', max_length=32)),
                ('size', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('centroid_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('category_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('classifier_score', models.FloatField(default=0.0)),
                ('investigation_count', models.PositiveIntegerField(default=0)),
                ('last_investigated_at', models.DateTimeField(blank=True, null=True)),
                ('last_refined_at', models.DateTimeField(blank=True, null=True)),
                ('merge_history', models.JSONField(blank=True, default=list)),
                ('merged_into_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absorbed_clusters', to='clusters.cluster')),
                ('split_from_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_children', to='clusters.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('hacker_news', 'Hacker News'), ('github', 'GitHub'), ('stack_overflow', 'Stack Overflow'), ('product_hunt', 'Product Hunt'), ('reddit', 'Reddit'), ('other', 'Other')], max_length=32)),
                ('source_item_id', models.CharField(db_index=True, max_length=256)),
                ('url', models.URLField(max_length=1024)),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=256, null=True)),
                ('posted_at', models.DateTimeField()),
                ('raw_text', models.TextField()),
                ('snippet', models.CharField(max_length=200)),
                ('classifier_verdict', models.CharField(choices=[('opportunity', 'Opportunity'), ('not_opportunity', 'Not opportunity')], max_length=32)),
                ('classifier_confidence', models.FloatField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('added_to_cluster_at', models.DateTimeField()),
                ('assigned_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clusters.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterMergeProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('centroid_similarity', models.FloatField()),
                ('llm_judge_verdict', models.BooleanField(blank=True, null=True)),
                ('llm_judge_confidence', models.FloatField(blank=True, null=True)),
                ('llm_judge_reasoning', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('superseded', 'Superseded')], default='pending_review', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('cluster_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_proposals_a', to='clusters.cluster')),
                ('cluster_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_proposals_b', to='clusters.cluster')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_proposals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterSplitProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sub_cluster_assignments', models.JSONField(default=dict)),
                ('internal_variance', models.FloatField()),
                ('llm_judge_verdict', models.BooleanField(blank=True, null=True)),
                ('llm_judge_confidence', models.FloatField(blank=True, null=True)),
                ('llm_judge_reasoning', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('superseded', 'Superseded')], default='pending_review', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_proposals', to='clusters.cluster')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_proposals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='cluster',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['centroid_embedding'], m=16, name='cluster_centroid_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='cluster',
            index=models.Index(fields=['status', 'last_seen_at'], name='clusters_cl_status_793e53_idx'),
        ),
        migrations.AddIndex(
            model_name='clusteritem',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='cluster_item_emb_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='clusteritem',
            index=models.Index(fields=['source', 'source_item_id'], name='clusters_cl_source_ee9b0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='clusteritem',
            constraint=models.UniqueConstraint(fields=('source', 'source_item_id'), name='cluster_item_source_unique'),
        ),
    ]
