# Generated by Django 6.0.5 on 2026-05-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='last_titled_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
