# Generated by Django 5.2.14 on 2026-05-25 02:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('investigations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_review', 'Awaiting review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('stale', 'Stale')], default='draft', max_length=24)),
                ('guidance', models.TextField(blank=True, default='')),
                ('output', models.JSONField(default=dict)),
                ('output_schema_version', models.CharField(default='1.0', max_length=16)),
                ('human_decision', models.JSONField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideations_decided', to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideations', to='investigations.investigation')),
                ('primary_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_ideations', to='agents.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['investigation', '-created_at'], name='ideation_id_investi_6621c5_idx'), models.Index(fields=['status'], name='ideation_id_status_38cc18_idx')],
            },
        ),
    ]
